[package]
name = "AptosExperimental"
version = "1.0.0"

[addresses]
std = "0x1"
aptos_framework = "0x1"

[dependencies]
AptosStdlib = { local = "../aptos-stdlib" }
MoveStdlib = { local = "../move-stdlib" }
